# Remote Cluster        
services:
  sc-remote:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sc-remote
    hostname: sc-remote
    environment:
      - RUST_LOG=info
    entrypoint: >
      /bin/sh -c "
      fluvio profile add docker 0.0.0.0:9003 docker;
      bash -c 'sleep 5 ; fluvio cluster spu register --id 5001 -p spu-remote:9010 --private-server spu-remote:9011' &
      ./fluvio-run sc --local /fluvio/metadata
      "
    volumes:
      - ./remote/fluvio-metadata:/fluvio/metadata
    ports:
      - 9003:9003
  spu-remote:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spu-remote
    hostname: spu-remote
    volumes:
      - ./remote/fluvio-data:/fluvio/data
    ports:
      - 9010:9010
    environment:
      - RUST_LOG=info
    command: "./fluvio-run spu -i 5001 -p spu-remote:9010 -v spu-remote:9011 --sc-addr sc-remote:9004 --log-base-dir /fluvio/data"
    depends_on:
      - sc-remote